name: Release
on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed
      
jobs:
  release:
    if: "startsWith(github.event.head_commit.message, 'bump version')"
    runs-on: ubuntu-latest
    name: "Push some release"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Git User
        run: |
          git config user.name "GitHub Action [BOT]"
          git config user.email "github-action[bot]@github.com"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: body
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print version
        run: |
            VER=$(cat version)
            echo "VERSION=$VER" >> $GITHUB_ENV
      - name: Push tags 
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.VERSION }}
          files: |
            body.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
