
name: Draft release
run-name: Draft release ${{ inputs.next_version }}

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  draft_release:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'develop'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false
          changelog_increment_filename: body.md
      - name: Clean up body.md
        run: |
          head -n -3 body.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push using ssh
        run: |
          git branch -r
          git status
          git push origin main --tags
