name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump version')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Git User
        run: |
          git config user.name "GitHub Action [BOT]"
          git config user.email "github-action[bot]@github.com"
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          push: false
          git_redirect_stderr: true
          changelog_increment_filename: body.md
      - name: Push using ssh
        run: |
          git push origin main --tags
      - name: Push tags 
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: v${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Pushing back to development
        run: |
          git checkout develop
          git pull
          git merge origin/main
          git status
          git log -1 --name-status
          git push origin develop
